#############################################################################
# Makefile for building: pet_game
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  pet_game.pro
# Template: app
# Command: /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/qmake -o Makefile pet_game.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/arm-linux-gcc
CXX           = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5 -I/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtWidgets -I/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtGui -I/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/qt5/QtCore -I. -I/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/linux-buildroot-g++
QMAKE         = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/qmake -install qinstall
QINSTALL_PROGRAM = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pet_game1.0.0
DISTDIR = /ad/eng/users/r/y/ryin2/EC535/lab5/sad/csmart/.tmp/pet_game1.0.0
LINK          = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/arm-linux-g++
LFLAGS        = --sysroot=/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot -Wl,-O1
LIBS          = $(SUBLIBS) -latomic /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Widgets.so /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Gui.so /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQt5Core.so -lpthread  -lrt -lpthread -ldl 
AR            = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/arm-linux-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/arm-linux-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Pet.cpp qrc_sprites.cpp
OBJECTS       = main.o \
		Pet.o \
		qrc_sprites.o
DIST          = /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/spec_pre.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/unix.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/linux.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/sanitize.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/gcc-base.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/gcc-base-unix.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/g++-base.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/g++-unix.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/qdevice.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/device_config.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/common/linux_device_pre.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/linux-buildroot-g++/arch.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/common/linux_device_post.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/qconfig.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_charts.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_charts_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_concurrent.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_concurrent_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_core.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_core_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_edid_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_fb_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_gui.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_gui_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_input_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_network.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_network_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_printsupport.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_printsupport_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qml.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qml_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlmodels.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmltest.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmltest_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quick.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quick_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickwidgets.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_service_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_sql.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_sql_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_svg.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_svg_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_testlib.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_testlib_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_theme_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_websockets.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_websockets_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_widgets.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_widgets_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_xml.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_xml_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_zlib_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt_functions.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt_config.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/linux-buildroot-g++/qmake.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/exclusive_builds.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/toolchain.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/default_pre.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resolve_config.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/default_post.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/warn_on.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resources_functions.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resources.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/moc.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/uic.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/unix/thread.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qmake_use.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/file_copies.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/testcase_targets.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/exceptions.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/yacc.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/lex.prf \
		pet_game.pro  main.cpp \
		Pet.cpp
QMAKE_TARGET  = pet_game
DESTDIR       = 
TARGET        = pet_game


first: all
####### Build rules

pet_game:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pet_game.pro /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/linux-buildroot-g++/qmake.conf /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/spec_pre.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/unix.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/linux.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/sanitize.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/gcc-base.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/gcc-base-unix.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/g++-base.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/g++-unix.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/qdevice.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/device_config.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/common/linux_device_pre.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/linux-buildroot-g++/arch.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/common/linux_device_post.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/qconfig.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_charts.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_charts_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_concurrent.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_concurrent_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_core.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_core_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_edid_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_fb_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_gui.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_gui_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_input_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_network.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_network_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_printsupport.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_printsupport_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qml.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qml_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlmodels.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmltest.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmltest_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quick.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quick_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickwidgets.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_service_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_sql.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_sql_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_svg.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_svg_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_testlib.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_testlib_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_theme_support_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_websockets.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_websockets_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_widgets.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_widgets_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_xml.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_xml_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_zlib_private.pri \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt_functions.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt_config.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/linux-buildroot-g++/qmake.conf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/exclusive_builds.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/toolchain.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/default_pre.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resolve_config.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/default_post.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/warn_on.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resources_functions.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resources.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/moc.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/uic.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/unix/thread.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qmake_use.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/file_copies.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/testcase_targets.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/exceptions.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/yacc.prf \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/lex.prf \
		pet_game.pro \
		sprites.qrc
	$(QMAKE) -o Makefile pet_game.pro
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/spec_pre.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/unix.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/linux.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/sanitize.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/gcc-base.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/gcc-base-unix.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/g++-base.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/common/g++-unix.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/qdevice.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/device_config.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/common/linux_device_pre.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/linux-buildroot-g++/arch.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/common/linux_device_post.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/qconfig.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_bootstrap_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_charts.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_charts_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_concurrent.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_concurrent_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_core.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_core_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_edid_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_fb_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_gui.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_gui_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_input_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_network.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_network_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_printsupport.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_printsupport_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qml.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qml_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmldebug_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlmodels.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmltest.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmltest_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quick.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quick_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickshapes_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickwidgets.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_service_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_sql.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_sql_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_svg.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_svg_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_testlib.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_testlib_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_theme_support_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_websockets.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_websockets_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_widgets.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_widgets_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_xml.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_xml_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/modules/qt_lib_zlib_private.pri:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt_functions.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt_config.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/devices/linux-buildroot-g++/qmake.conf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/spec_post.prf:
../.qmake.stash:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/exclusive_builds.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/toolchain.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/default_pre.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resolve_config.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/default_post.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/warn_on.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qt.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resources_functions.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/resources.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/moc.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/uic.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/unix/thread.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/qmake_use.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/file_copies.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/testcase_targets.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/exceptions.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/yacc.prf:
/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/lex.prf:
pet_game.pro:
sprites.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile pet_game.pro

qmake_all: FORCE


all: Makefile pet_game

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents sprites.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Pet.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_sprites.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_sprites.cpp
qrc_sprites.cpp: sprites.qrc \
		/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/rcc \
		sprites/FishCat7.png \
		sprites/CatBall9.png \
		sprites/AvoCato2.png \
		sprites/CatSmol7.png \
		sprites/FishCat10.png \
		sprites/CatSmol13.png \
		sprites/CatBall12.png \
		sprites/Jiji1.png \
		sprites/FishCat2.png \
		sprites/Carton.png \
		sprites/CatBall4.png \
		sprites/CatSmol2.png \
		sprites/CatSmol17.png \
		sprites/FishCat6.png \
		sprites/CatBall8.png \
		sprites/AvoCato1.png \
		sprites/PaperBag.png \
		sprites/CatSmol6.png \
		sprites/Catsby2.png \
		sprites/CatSmol12.png \
		sprites/CatBall11.png \
		sprites/AristoCat2.png \
		sprites/FishCat1.png \
		sprites/BusinessCat1.png \
		sprites/CatBall3.png \
		sprites/Eggo.png \
		sprites/CatSmol16.png \
		sprites/FishCat5.png \
		sprites/PopCat2.png \
		sprites/CatBall7.png \
		sprites/CatSmol5.png \
		sprites/Catsby1.png \
		sprites/CatSmol11.png \
		sprites/CatBall10.png \
		sprites/AristoCat1.png \
		sprites/FishCat9.png \
		sprites/CatBall2.png \
		sprites/EggCrack.png \
		sprites/CatSmol9.png \
		sprites/CATcus2.png \
		sprites/Rock2.png \
		sprites/CatSmol15.png \
		sprites/CatGpt.png \
		sprites/FishCat4.png \
		sprites/DiscoCat2.png \
		sprites/CatBall6.png \
		sprites/PopCat1.png \
		sprites/Curdo2.png \
		sprites/RightCrack.png \
		sprites/CatSmol4.png \
		sprites/CatSmol10.png \
		sprites/CatSmol19.png \
		sprites/FishCat8.png \
		sprites/CatBall1.png \
		sprites/CatSmol8.png \
		sprites/CATcus1.png \
		sprites/Rock1.png \
		sprites/CatSmol14.png \
		sprites/Catsmol1.png \
		sprites/Jiji2.png \
		sprites/FishCat3.png \
		sprites/CatSmol20.png \
		sprites/DiscoCat1.png \
		sprites/CatBall5.png \
		sprites/Curdo1.png \
		sprites/CatSmol3.png \
		sprites/LeftCrack.png \
		sprites/BusnissCat2.png \
		sprites/CatSmol18.png
	/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/rcc -name sprites sprites.qrc -o qrc_sprites.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/data/dummy.cpp
	/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/bin/arm-linux-g++ -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/arm-buildroot-linux-gnueabihf/sysroot -Wall -Wextra -dM -E -o moc_predefs.h /ad/eng/courses/ec/ec535/bbb/buildroot-2021.02.1/output/host/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp Pet.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Pet.o: Pet.cpp Pet.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pet.o Pet.cpp

qrc_sprites.o: qrc_sprites.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_sprites.o qrc_sprites.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/ad/eng/users/r/y/ryin2/EC535/lab5/sad/csmart/. || mkdir -p $(INSTALL_ROOT)/ad/eng/users/r/y/ryin2/EC535/lab5/sad/csmart/.
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/ad/eng/users/r/y/ryin2/EC535/lab5/sad/csmart/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/ad/eng/users/r/y/ryin2/EC535/lab5/sad/csmart/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/ad/eng/users/r/y/ryin2/EC535/lab5/sad/csmart/./ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

